stages:
  - validate
  - plan
  - apply
  - destroy
image:
  name: hashicorp/terraform:light
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
variables:
  TERRAFORM_MODULE_DIR: ${CI_PROJECT_DIR}    # The relative path to the root directory of the Terraform project.
  TERRAFORM_MODULE_NAME: ${CI_PROJECT_NAME}  # The name of your Terraform module, must not have any spaces or underscores (will be translated to hyphens).
  TERRAFORM_MODULE_SYSTEM: local             # The system or provider your Terraform module targets (ex. local, aws, google).
  TERRAFORM_MODULE_VERSION: ${CI_COMMIT_TAG} # The version - it's recommended to follow SemVer for Terraform Module Versioning.
before_script:
  - cp .terraformrc /root/.terraformrc
  - rm -rf .terraform
  - terraform --version
  - export GITLAB_ACCESS_TOKEN=$GITLAB_TOCKEN
  - sed -i "s/__TOKEN__/$TOKEN/" variables.tf
  - terraform init
validate:
  stage: validate
  script:
    - terraform validate
plan:
  stage: plan
  script:
    - terraform plan -out "planfile"
  dependencies:
    - validate
  artifacts:
    paths:
      - planfile
apply:
  stage: apply
  script:
    - terraform apply -auto-approve "planfile" 
  dependencies:
    - plan
  when: manual

destroy:
  stage: destroy
  script:
    - terraform init
    - terraform destroy -auto-approve
  dependencies:
    - apply
  when: manual
